/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/auth/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Login */
    post: operations['login'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Logout */
    post: operations['logout'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Me */
    get: operations['current_user'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/entries/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Entries */
    get: operations['list_entries'];
    put?: never;
    /** Create Entry */
    post: operations['create_entry'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/entries/batch/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create Entries */
    post: operations['create_entries'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/entries/by-url/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Entry By Url
     * @description Answer the entry held at *url*, so a client can compare.
     *
     *     Posting is an upsert, which leaves a client no way to ask what an
     *     address currently says before writing over it. Listing and filtering
     *     client-side is the wrong shape once somebody holds thousands of
     *     entries.
     *
     *     Declared before any /{id}/ route: whoever adds one must keep it
     *     below this, or "by-url" will be read as an id.
     */
    get: operations['get_entry_by_url'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Health
     * @description Report that the service is up, in the caller's language.
     */
    get: operations['health'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** BatchError */
    BatchError: {
      /** Code */
      code: string;
      /** Details */
      details?: {
        [key: string]: unknown;
      };
      /** Message */
      message: string;
    };
    /** BatchOut */
    BatchOut: {
      /** Results */
      results: components['schemas']['BatchResult'][];
    };
    /**
     * BatchResult
     * @description One row of a batch, in the order it was submitted.
     */
    BatchResult: {
      error?: components['schemas']['BatchError'] | null;
      /** Id */
      id?: number | null;
      /** Index */
      index: number;
      /** Status */
      status: string;
    };
    /**
     * EntryIn
     * @description Everything but the address has a default.
     *
     *     A minimal client can post {"url": "..."} and nothing else, which
     *     matters more once custom fields arrive.
     */
    EntryIn: {
      /** Fields */
      fields?: {
        [key: string]: unknown;
      } | null;
      /**
       * Notes
       * @default
       */
      notes?: string;
      /** Tags */
      tags?: string[];
      /**
       * Title
       * @default
       */
      title?: string;
      /** Url */
      url: string;
    };
    /** EntryOut */
    EntryOut: {
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Fields */
      fields: {
        [key: string]: string;
      };
      /** Id */
      id: number;
      /** Notes */
      notes: string;
      /** Tags */
      tags: string[];
      /** Title */
      title: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
      /** Url */
      url: string;
    };
    /** HealthOut */
    HealthOut: {
      /** Message */
      message: string;
      /** Service */
      service: string;
      /** Status */
      status: string;
      /** Version */
      version: string;
    };
    /** Input */
    Input: {
      /**
       * Limit
       * @default 100
       */
      limit?: number;
      /**
       * Offset
       * @default 0
       */
      offset?: number;
    };
    /** LoginIn */
    LoginIn: {
      /** Identifier */
      identifier: string;
      /** Password */
      password: string;
    };
    /** PagedEntryOut */
    PagedEntryOut: {
      /** Count */
      count: number;
      /** Items */
      items: components['schemas']['EntryOut'][];
    };
    /** UserOut */
    UserOut: {
      /** Display Name */
      display_name: string | null;
      /** Email */
      email: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginIn'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserOut'];
        };
      };
    };
  };
  logout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  current_user: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserOut'];
        };
      };
    };
  };
  list_entries: {
    parameters: {
      query?: {
        limit?: number;
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PagedEntryOut'];
        };
      };
    };
  };
  create_entry: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['EntryIn'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['EntryOut'];
        };
      };
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['EntryOut'];
        };
      };
    };
  };
  create_entries: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['EntryIn'][];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['BatchOut'];
        };
      };
      /** @description Multi-Status */
      207: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['BatchOut'];
        };
      };
    };
  };
  get_entry_by_url: {
    parameters: {
      query: {
        url: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['EntryOut'];
        };
      };
    };
  };
  health: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HealthOut'];
        };
      };
    };
  };
}
