/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/auth/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Login */
    post: operations['login'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Logout */
    post: operations['logout'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Me */
    get: operations['current_user'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/tokens': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Create Api Token
     * @description Make a bearer token for a script or another client.
     *
     *     Session-authenticated only. A token that could mint tokens would
     *     make revoking a leaked one pointless: the holder would simply issue
     *     a replacement, and the original could be revoked without ending
     *     their access.
     */
    post: operations['create_api_token'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/tokens/exchange': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Exchange Credentials For Token
     * @description Trade an email address and password for a bearer token.
     *
     *     For clients that cannot hold a session. A browser extension is the
     *     case: Firefox sends `Origin: moz-extension://<uuid>` on every
     *     request, the uuid differs per install so it cannot be trusted in
     *     advance, and Django refuses the origin before it reads anything
     *     else — so an extension can sign in and then do nothing unsafe with
     *     the session it got.
     *
     *     This route reads no session at all, which is also what makes it
     *     safe without a CSRF check: there is no path through it that a
     *     cookie alone can take. A signed-in browser gains nothing here.
     */
    post: operations['exchange_credentials_for_token'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/entries/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Entries */
    get: operations['list_entries'];
    put?: never;
    /** Create Entry */
    post: operations['create_entry'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/entries/batch/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create Entries */
    post: operations['create_entries'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/entries/by-url/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Entry By Url
     * @description Answer the entry held at *url*, so a client can compare.
     *
     *     Posting is an upsert, which leaves a client no way to ask what an
     *     address currently says before writing over it. Listing and filtering
     *     client-side is the wrong shape once somebody holds thousands of
     *     entries.
     *
     *     Declared before any /{id}/ route: whoever adds one must keep it
     *     below this, or "by-url" will be read as an id.
     */
    get: operations['get_entry_by_url'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/entries/{pk}/image': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Upload Entry Image
     * @description Attach an uploaded picture, replacing any the entry had.
     *
     *     Multipart rather than JSON: base64 in a body would inflate every
     *     upload by a third for no gain.
     */
    post: operations['upload_entry_image'];
    /** Delete Entry Image */
    delete: operations['delete_entry_image'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/fields/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Fields
     * @description The fields this account's entries may carry.
     *
     *     A client reads these to build its own inputs: the kind says what
     *     sort of value is wanted, and a choice field's options say what the
     *     choices are.
     */
    get: operations['list_fields'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Health
     * @description Report that the service is up, in the caller's language.
     */
    get: operations['health'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/labels/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Labels
     * @description This account's labels, optionally those beginning with a string.
     *
     *     The same endpoint serves a full list and an autocomplete, because
     *     they differ only by a filter. `count` is how many labels match,
     *     not how many this page carries, so a client knows whether to ask
     *     for more.
     */
    get: operations['list_labels'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** BatchError */
    BatchError: {
      /** Code */
      code: string;
      /** Details */
      details?: {
        [key: string]: unknown;
      };
      /** Message */
      message: string;
    };
    /** BatchOut */
    BatchOut: {
      /** Results */
      results: components['schemas']['BatchResult'][];
    };
    /**
     * BatchResult
     * @description One row of a batch, in the order it was submitted.
     */
    BatchResult: {
      error?: components['schemas']['BatchError'] | null;
      /** Id */
      id?: number | null;
      /** Index */
      index: number;
      /** Status */
      status: string;
    };
    /**
     * EntryIn
     * @description Everything but the address has a default.
     *
     *     A minimal client can post {"url": "..."} and nothing else, which
     *     matters more once custom fields arrive.
     */
    EntryIn: {
      /** Fields */
      fields?: {
        [key: string]: unknown;
      } | null;
      /** Image Url */
      image_url?: string | null;
      /**
       * Notes
       * @default
       */
      notes?: string;
      /** Tags */
      tags?: string[];
      /**
       * Title
       * @default
       */
      title?: string;
      /** Url */
      url: string;
    };
    /** EntryOut */
    EntryOut: {
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Fields */
      fields: {
        [key: string]: string;
      };
      /** Id */
      id: number;
      image: components['schemas']['ImageOut'] | null;
      /** Notes */
      notes: string;
      /** Tags */
      tags: string[];
      /** Title */
      title: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
      /** Url */
      url: string;
    };
    /**
     * FieldOut
     * @description One of the fields this account's entries may carry.
     *
     *     `name` is the key: it is what an entry's `fields` object uses, so a
     *     client writes back what it read here. `options` is empty except
     *     for a choice field, where it is the only way to know what the
     *     choices are.
     */
    FieldOut: {
      /** Kind */
      kind: string;
      /** Name */
      name: string;
      /** Options */
      options: string[];
    };
    /** HealthOut */
    HealthOut: {
      /** Message */
      message: string;
      /** Service */
      service: string;
      /** Status */
      status: string;
      /** Version */
      version: string;
    };
    /**
     * ImageOut
     * @description What a client needs to show the picture, and nothing more.
     *
     *     Neither copy of the bytes appears here. The original is archival
     *     and never leaves the server; the display copy is fetched from
     *     `url`, which is access-controlled.
     */
    ImageOut: {
      /** Height */
      height: number;
      /** Url */
      url: string;
      /** Width */
      width: number;
    };
    /** Input */
    Input: {
      /**
       * After
       * @default
       */
      after?: string;
      /**
       * Limit
       * @default 1000
       */
      limit?: number;
    };
    /**
     * LabelOut
     * @description A label already in use on this account's entries.
     */
    LabelOut: {
      /** Name */
      name: string;
    };
    /** LoginIn */
    LoginIn: {
      /** Identifier */
      identifier: string;
      /** Password */
      password: string;
    };
    /** PagedEntryOut */
    PagedEntryOut: {
      /** Count */
      count: number;
      /** Items */
      items: components['schemas']['EntryOut'][];
    };
    /** PagedFieldOut */
    PagedFieldOut: {
      /** Count */
      count: number;
      /** Items */
      items: components['schemas']['FieldOut'][];
    };
    /** PagedLabelOut */
    PagedLabelOut: {
      /** Count */
      count: number;
      /** Items */
      items: components['schemas']['LabelOut'][];
    };
    /**
     * TokenCreateIn
     * @description A name, and optionally a date it should stop working.
     */
    TokenCreateIn: {
      /** Expires At */
      expires_at?: string | null;
      /** Name */
      name: string;
    };
    /**
     * TokenExchangeIn
     * @description Credentials traded for a token, for a client with no session.
     *
     *     `identifier` and `password` are the same pair `login` takes; the
     *     name is the one the clients page will show beside the token.
     */
    TokenExchangeIn: {
      /** Expires At */
      expires_at?: string | null;
      /** Identifier */
      identifier: string;
      /** Name */
      name: string;
      /** Password */
      password: string;
    };
    /**
     * TokenOut
     * @description The only time the raw token exists outside the client.
     *
     *     Only a hash is stored, so a client that loses this value has to
     *     make another token; nobody can look it up, including whoever runs
     *     this Hrček.
     */
    TokenOut: {
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Expires At */
      expires_at: string | null;
      /** Id */
      id: number;
      /** Name */
      name: string;
      /** Token */
      token: string;
    };
    /** UserOut */
    UserOut: {
      /** Display Name */
      display_name: string | null;
      /** Email */
      email: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginIn'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserOut'];
        };
      };
    };
  };
  logout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  current_user: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserOut'];
        };
      };
    };
  };
  create_api_token: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['TokenCreateIn'];
      };
    };
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TokenOut'];
        };
      };
    };
  };
  exchange_credentials_for_token: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['TokenExchangeIn'];
      };
    };
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TokenOut'];
        };
      };
    };
  };
  list_entries: {
    parameters: {
      query?: {
        limit?: number;
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PagedEntryOut'];
        };
      };
    };
  };
  create_entry: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['EntryIn'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['EntryOut'];
        };
      };
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['EntryOut'];
        };
      };
    };
  };
  create_entries: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['EntryIn'][];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['BatchOut'];
        };
      };
      /** @description Multi-Status */
      207: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['BatchOut'];
        };
      };
    };
  };
  get_entry_by_url: {
    parameters: {
      query: {
        url: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['EntryOut'];
        };
      };
    };
  };
  upload_entry_image: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        pk: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'multipart/form-data': {
          /**
           * File
           * Format: binary
           */
          file: string;
        };
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['EntryOut'];
        };
      };
    };
  };
  delete_entry_image: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        pk: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  list_fields: {
    parameters: {
      query?: {
        limit?: number;
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PagedFieldOut'];
        };
      };
    };
  };
  health: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HealthOut'];
        };
      };
    };
  };
  list_labels: {
    parameters: {
      query?: {
        starts_with?: string;
        limit?: number;
        after?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PagedLabelOut'];
        };
      };
    };
  };
}
